apiVersion: v1
kind: Service
metadata:
  name: docscope
  namespace: docscope
  labels:
    app: docscope
    component: api
spec:
  type: ClusterIP
  selector:
    app: docscope
    component: api
  ports:
  - name: api
    port: 8000
    targetPort: api
    protocol: TCP
  - name: ui
    port: 8080
    targetPort: ui
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
apiVersion: v1
kind: Service
metadata:
  name: docscope-nodeport
  namespace: docscope
  labels:
    app: docscope
    component: api
spec:
  type: NodePort
  selector:
    app: docscope
    component: api
  ports:
  - name: api
    port: 8000
    targetPort: api
    nodePort: 30800
    protocol: TCP
  - name: ui
    port: 8080
    targetPort: ui
    nodePort: 30808
    protocol: TCP